# Generated by Django 3.0.6 on 2020-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSFR',
            fields=[
                ('Name', models.CharField(max_length=25)),
                ('Father_name', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=1)),
                ('SAP_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Batch', models.CharField(max_length=4)),
                ('Address', models.TextField(max_length=100)),
                ('DOB', models.DateField(default=None)),
                ('Department', models.CharField(max_length=10)),
                ('Degree', models.CharField(max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('Employee', models.BooleanField()),
                ('Images', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
