# Generated by Django 3.0.6 on 2020-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csfr',
            name='SAP_ID',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
